services:
  minio:
    image: quay.io/minio/aistor/minio:latest
    container_name: minio
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - "${HOME}/minio/data:/mnt/data"
      - "./backend/db/minio.license:/minio.license:ro"
    command: ["minio", "server", "/mnt/data", "--license", "/minio.license"]
    restart: unless-stopped
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # sonarqube:
  #   image: sonarqube:community
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_logs:/opt/sonarqube/logs

volumes:
  postgres_data:
  # sonarqube_data:
  # sonarqube_logs: