services:
  minio:
    image: quay.io/minio/aistor/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "${HOME}/minio/data:/mnt/data"
      - "./minio.license:/backend/db/minio.license:ro"
    command: ["minio", "server", "/mnt/data", "--license", "/minio.license"]
    restart: unless-stopped
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: